os: linux
language: python
dist: "bionic"
python:
  - '3.5'
install:
  - pip install -r requirements.txt
  - pip install coverage unittest2
  - pip install codecov
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=attila tests/
# Push the results back to codecov
after_success:
  - codecov
deploy:
  provider: pypi
  username: __token__
  password:
    secure: iEoamkMS5V0VTLY/76zQSAPN0YVLMZMt4gueHY/7mfTaJeu8DykuGrqkAPLFwwmtLoj4aDbISi2yxxZgK6mUMFralWwfaS4ET0S28Ta8bMfRjzrORIqgU1JuxmBufJ3V2JGJ+3yoCuywQkpSIEqOYUIG89Jhy/UYmmYI4xLVaN54bk5xu1NKdJhCBQ+82tQghBxl2bq3H2F6EEGfnDL2AFzwRl/5X2XstmlzP2OXWuUsN/qW3HNkOpA79m+kj/XaiOVmNha0azBz5he/nxjkmHZCHdp3LO6uydhOFYy9eTPSZ2iWaR+4Ps+Kr2aNTaFvCpD01XGOUkoBVPXSKKYsswIFE/ulmuX1hKjlfy6Xd2ooD8vPIClFYRias8yChti3Y1MDOAjKfNWs9GLXzNJ6W44A29RtcxjtdWt78JEWfBBXMFwULIfoJFfmbJ/U4S24YFQZmISBVsewM+l2U75jiSMFg2bmbRGh6MbrSuwnt2sUly0TLntT1ykVGUVlKiKlk4R2SdxG34A7EuoPPuWlduIWswcvogUFGL8i7AfhgPlnYlKSaaZVL9SYbMAda7muGSLME+HRu7lE0pEKPrdBXaC9BOYRixa++bzG31Rg0jvwW0OT1KUhQLMe8IX0gkNhY97/Nsm+GrB3MzQII96AR3iYACYUFGWaok+3C+eBit0=
  on:
    tags: true
